server:
  port: 8840

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug
    com:
      ovft:
        access:
          sys:
            dao: debug

spring:
  application:
    name: heritage
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.165.251/heritage?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 20190722
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location:
      max-file-size: 500kb
      max-request-size: 10MB
  http:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB


qiniuyun:
  accessKey: RgylyW1vR0eqiPV2YjKX1avdm-IRiXHSqt0wlyac
  secretKey: 5Ro9To9jdMi_nigRYkrj9bHGNCKV4I0bsRIiEEnO
  bucket: youxiaoyun
  filePrefix: fineCourse/
